### ISSUE TITLE
Partial file usecases question

### ISSUE THREAD

**Issue by zielu** [ternjs/tern#716]
Hi, I was wondering what kind of changes are supported by partial file update.
Specifically I'm interested in multi-line changes. Let's assume I have a file with 5 lines A, B, C, D, E.
If line C is removed can I send offset of B and B, D of should I send entire file ?
The same scenario is also possible with additions.

I'm asking because I encountered issues while repeatedly sending full files with minimal changes - nodejs memory just keeps climbing and is never released.

**Comment by marijnh** [comment]
For small files (say <500 lines), definitely always use full file updates, since partial updates do have a bunch of buggy corner cases.

A partial update should be a single chunk, so you would have to send BCD along with B's offset. You can include two partial updates in your request, if you really want, but again, don't get too fine-grained, this isn't going to have a good effect on the result quality.
