### ISSUE TITLE
Some proposals are missing when filtering is turned off

### ISSUE THREAD

**Issue by mrennie** [ternjs/tern#790]
Consider the following snippet:

```var x = { the : 1, far : this.th };```

if you issue a completions request at the end of the ```this.th``` member expression with the filter property set to true (the default) you get back "the" as a proposal. But if you set the filter property to false, you do not.

I would expect to get "the" in both cases - the default case because its a prefix of the property, and the no-filter case because I want to do the filtering on the client side.

An example request that causes "the" to not be returned (where the snippet above is the content of "test_file_name.js"):

```{type: "completions", file: "test_file_name.js", end: 32, types: true, filter: false}```

**Comment by marijnh** [comment]
That's because `the` in this case is coming from a fallback strategy ('try all property names we've seen') which is only tried when no other results are found. `this` in your code refers to the global scope, which does not have a `the` property. I don't think it would be useful to activate this fallback strategy by default when `filter` is false, so the behavior you're seeing is intentional.
