### ISSUE TITLE
flowtype support

### ISSUE THREAD

**Issue by rattrayalex** [ternjs/tern#827]
Does this support Flow? Could this be used as a replacement for Flow's editor integration?

**Comment by marijnh** [comment]
No. If you write Flow code, you're much better off using Flow's tools.

**Comment by rattrayalex** [comment]
Thanks! Appreciate the quick response!

**Comment by deltaskelta** [comment]
I would just like to add something to this for anyone who stumbled here through google...

While tern does not support flow, it might benefit you to still use it alongside the flow tools because the flow tools only work on package that were written in flow or converted to have an accompanying `.js.flow` type file with it. Valid Javascript is valid FlowType, but valid FlowType is not valid Javascript. 

If you only use flow tools, you will run into a case where you want to import regular javascript and there are no flowtyped files for it which means you lose all of the tooling. Run them side by side and tern makes a nice fallback for when the flow tools cannot help you.

**Comment by fxfactorial** [comment]
It would be good if tern could understand as extension a flow type of 

```
import type {$Foo} from 'pkg';
```

and then use that info as well, my usecase is auto completion of tern in emacs and flow auto completion support there is terrible, tern works much better.
