### ISSUE TITLE
Can't generate json for p5.js library using condense

### ISSUE THREAD

**Issue by ducklin5** [ternjs/tern#872]
```
****@**** MINGW64 ~/AppData/Roaming/Brackets/extensions/user/ternific/node_modules/tern/bin $ ./condense --name p /c/wamp/www/libraries/p5.js
{
  "!name": "p"
}
```
Can't generate json for p5.js library using condense. I'm using tern in Brackets editor and Im trying to get p5.js autocomplete. Ive ran the same command with jquery and it works fine.

**Comment by marijnh** [comment]
I guess Tern has problems with the bundled output in p5.js. I don't know exactly why, but if you feel like simplifying the file to reduce the testcase in order to find out what aspect causes the problem, I'd be interested in the result. As it is, I don't have time to poke at random libraries to figure out which aspect of them breaks Tern.

**Comment by 8-uh** [comment]
I've also been attempting this. However, I'm running it on the source files. 
If you run condense on each file individually, it works just fine...  but running this command:
`$ ./node_modules/tern/bin/condense --plugin node --plugin modules --plugin requirejs --plugin doc_comment src/app.js`

only produces:
```
{
  "!name": "src/app.js"
}
```

**Comment by anhtuann** [comment]
Any news about this matter ? I would love to have autocompletion with p5js

**Comment by ducklin5** [comment]
There are presumably other ways to do this now. I think this can be closed.
